// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ShipmentSonKn
{
    public int ShipmentSonKnid { get; set; }

    public string TrackingNumber { get; set; }

    public string ShippingCompany { get; set; }

    public DateOnly? ShippedDate { get; set; }

    public DateOnly? DeliveredDate { get; set; }

    public bool? IsDelivered { get; set; }

    public virtual ICollection<ProductionSonKn> ProductionSonKns { get; set; } = new List<ProductionSonKn>();
}