// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class CustomerSupportQuiTh
{
    public int SupportQuiThid { get; set; }

    public int OrderQuiThid { get; set; }

    public int CustomerId { get; set; }

    public int StaffId { get; set; }

    public int? ReviewQuiThid { get; set; }

    public string IssueType { get; set; }

    public string Resolution { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual UserAccount Customer { get; set; }

    public virtual OrderNamtmh OrderQuiTh { get; set; }

    public virtual OrderReviewQuiTh ReviewQuiTh { get; set; }

    public virtual UserAccount Staff { get; set; }
}