// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class OrderReviewQuiTh
{
    public int ReviewQuiThid { get; set; }

    public int OrderQuiThid { get; set; }

    public int StaffId { get; set; }

    public int? PrescriptionId { get; set; }

    public string ReviewType { get; set; }

    public string ReviewStatus { get; set; }

    public string IssueNote { get; set; }

    public bool? CustomerContacted { get; set; }

    public string ContactMethod { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CustomerSupportQuiTh> CustomerSupportQuiThs { get; set; } = new List<CustomerSupportQuiTh>();

    public virtual OrderNamtmh OrderQuiTh { get; set; }

    public virtual PrescriptionPhuHn Prescription { get; set; }

    public virtual UserAccount Staff { get; set; }
}