// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class OrderItemNamtmh
{
    public int OrderItemNamtmhId { get; set; }

    public int OrderNamtmhId { get; set; }

    public int ProductTriChid { get; set; }

    public int VariantId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public int? PrescriptionId { get; set; }

    public virtual OrderNamtmh OrderNamtmh { get; set; }

    public virtual ICollection<PrescriptionPhuHn> PrescriptionPhuHns { get; set; } = new List<PrescriptionPhuHn>();

    public virtual ProductTriCh ProductTriCh { get; set; }
}