// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class OrderNamtmh
{
    public int OrderNamtmhId { get; set; }

    public string OrderNumber { get; set; }

    public int CustomerId { get; set; }

    public string OrderType { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? ShippingFee { get; set; }

    public decimal FinalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string ShippingAddress { get; set; }

    public string OrderStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AfterSalesTaiNd> AfterSalesTaiNds { get; set; } = new List<AfterSalesTaiNd>();

    public virtual UserAccount Customer { get; set; }

    public virtual ICollection<CustomerSupportQuiTh> CustomerSupportQuiThs { get; set; } = new List<CustomerSupportQuiTh>();

    public virtual ICollection<OrderItemNamtmh> OrderItemNamtmhs { get; set; } = new List<OrderItemNamtmh>();

    public virtual ICollection<OrderReviewQuiTh> OrderReviewQuiThs { get; set; } = new List<OrderReviewQuiTh>();

    public virtual ICollection<PrescriptionPhuHn> PrescriptionPhuHns { get; set; } = new List<PrescriptionPhuHn>();

    public virtual ICollection<ProductReviewMiLtt> ProductReviewMiLtts { get; set; } = new List<ProductReviewMiLtt>();

    public virtual ICollection<ProductionSonKn> ProductionSonKns { get; set; } = new List<ProductionSonKn>();
}