// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ProductReviewMiLtt
{
    public int ReviewMiLttid { get; set; }

    public int ProductId { get; set; }

    public int UserId { get; set; }

    public int OrderId { get; set; }

    public byte Rating { get; set; }

    public string Comment { get; set; }

    public bool? IsVerified { get; set; }

    public int? LikeCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrderNamtmh Order { get; set; }

    public virtual ProductTriCh Product { get; set; }

    public virtual ICollection<ReviewImageMiLtt> ReviewImageMiLtts { get; set; } = new List<ReviewImageMiLtt>();

    public virtual UserAccount User { get; set; }
}