// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ProductTriCh
{
    public int ProductTriChid { get; set; }

    public string ProductName { get; set; }

    public string Sku { get; set; }

    public int? CategoryTriChid { get; set; }

    public string Brand { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public string FrameType { get; set; }

    public string Material { get; set; }

    public string Dimensions { get; set; }

    public int? StockQuantity { get; set; }

    public byte? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CategoryTriCh CategoryTriCh { get; set; }

    public virtual ICollection<OrderItemNamtmh> OrderItemNamtmhs { get; set; } = new List<OrderItemNamtmh>();

    public virtual ICollection<ProductReviewMiLtt> ProductReviewMiLtts { get; set; } = new List<ProductReviewMiLtt>();
}