// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class UserAccount
{
    public int UserAccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; }

    public int? RoleId { get; set; }

    public string RequestCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AfterSalesTaiNd> AfterSalesTaiNds { get; set; } = new List<AfterSalesTaiNd>();

    public virtual ICollection<CustomerSupportQuiTh> CustomerSupportQuiThCustomers { get; set; } = new List<CustomerSupportQuiTh>();

    public virtual ICollection<CustomerSupportQuiTh> CustomerSupportQuiThStaffs { get; set; } = new List<CustomerSupportQuiTh>();

    public virtual ICollection<OrderNamtmh> OrderNamtmhs { get; set; } = new List<OrderNamtmh>();

    public virtual ICollection<OrderReviewQuiTh> OrderReviewQuiThs { get; set; } = new List<OrderReviewQuiTh>();

    public virtual ICollection<ProductReviewMiLtt> ProductReviewMiLtts { get; set; } = new List<ProductReviewMiLtt>();

    public virtual ICollection<ProductionSonKn> ProductionSonKns { get; set; } = new List<ProductionSonKn>();
}