// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class CategoryTriCh
{
    public int CategoryTriChid { get; set; }

    public string CategoryName { get; set; }

    public string Slug { get; set; }

    public int? ParentId { get; set; }

    public byte? Status { get; set; }

    public virtual ICollection<CategoryTriCh> InverseParent { get; set; } = new List<CategoryTriCh>();

    public virtual CategoryTriCh Parent { get; set; }

    public virtual ICollection<ProductTriCh> ProductTriChes { get; set; } = new List<ProductTriCh>();
}