// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ProductImageTriCh
{
    public int ImageTriChid { get; set; }

    public int ProductTriChid { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsPrimary { get; set; }

    public int? DisplayOrder { get; set; }

    public int? ColorTriChid { get; set; }

    public virtual ProductColorTriCh ColorTriCh { get; set; }

    public virtual ProductTriCh ProductTriCh { get; set; }
}