// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ReviewImageMiLtt
{
    public int ImageMiLttid { get; set; }

    public int ReviewMiLttid { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual ProductReviewMiLtt ReviewMiLtt { get; set; }
}