// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GlassStore.Entities.TriCH.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace GlassStore.Repositories.TriCH.DBContext;

public partial class PRN222_EYEWEARSHOPContext : DbContext
{
    public PRN222_EYEWEARSHOPContext()
    {
    }

    public PRN222_EYEWEARSHOPContext(DbContextOptions<PRN222_EYEWEARSHOPContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AfterSalesTaiNd> AfterSalesTaiNds { get; set; }

    public virtual DbSet<CategoryTriCh> CategoryTriChes { get; set; }

    public virtual DbSet<CustomerSupportQuiTh> CustomerSupportQuiThs { get; set; }

    public virtual DbSet<LensServicePhuHn> LensServicePhuHns { get; set; }

    public virtual DbSet<OrderItemNamtmh> OrderItemNamtmhs { get; set; }

    public virtual DbSet<OrderNamtmh> OrderNamtmhs { get; set; }

    public virtual DbSet<OrderReviewQuiTh> OrderReviewQuiThs { get; set; }

    public virtual DbSet<PrescriptionPhuHn> PrescriptionPhuHns { get; set; }

    public virtual DbSet<ProductReviewMiLtt> ProductReviewMiLtts { get; set; }

    public virtual DbSet<ProductTriCh> ProductTriChes { get; set; }

    public virtual DbSet<ProductionSonKn> ProductionSonKns { get; set; }

    public virtual DbSet<RefundTaiNd> RefundTaiNds { get; set; }

    public virtual DbSet<ReviewImageMiLtt> ReviewImageMiLtts { get; set; }

    public virtual DbSet<ShipmentSonKn> ShipmentSonKns { get; set; }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-T2SK0GG0;Initial Catalog=PRN222_EYEWEARSHOP;Persist Security Info=True;User ID=sa;Password=12345");

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AfterSalesTaiNd>(entity =>
        {
            entity.HasKey(e => e.RequestIdtaiNd).HasName("PK__AfterSal__D81F30C808901058");

            entity.ToTable("AfterSalesTaiND");

            entity.Property(e => e.RequestIdtaiNd).HasColumnName("requestIDTaiND");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerID");
            entity.Property(e => e.ExchangeProductId).HasColumnName("exchangeProductID");
            entity.Property(e => e.OrderId).HasColumnName("orderID");
            entity.Property(e => e.ProcessedAt)
                .HasColumnType("datetime")
                .HasColumnName("processedAt");
            entity.Property(e => e.ProcessedBy).HasColumnName("processedBy");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.RefundAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("refundAmount");
            entity.Property(e => e.RefundIdtaiNd).HasColumnName("refundIDTaiND");
            entity.Property(e => e.RequestStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("requestStatus");
            entity.Property(e => e.RequestType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("requestType");
            entity.Property(e => e.RequestedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("requestedAt");
            entity.Property(e => e.ResolutionNotes).HasColumnName("resolutionNotes");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Order).WithMany(p => p.AfterSalesTaiNds)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AfterSales_Order");

            entity.HasOne(d => d.ProcessedByNavigation).WithMany(p => p.AfterSalesTaiNds)
                .HasForeignKey(d => d.ProcessedBy)
                .HasConstraintName("FK_AfterSales_Staff");

            entity.HasOne(d => d.RefundIdtaiNdNavigation).WithMany(p => p.AfterSalesTaiNds)
                .HasForeignKey(d => d.RefundIdtaiNd)
                .HasConstraintName("FK_AfterSales_Refund");
        });

        modelBuilder.Entity<CategoryTriCh>(entity =>
        {
            entity.HasKey(e => e.CategoryTriChid).HasName("PK__Category__C09E7C99C0CD2CF2");

            entity.ToTable("CategoryTriCH");

            entity.HasIndex(e => e.Slug, "UQ__Category__32DD1E4C775AA27E").IsUnique();

            entity.Property(e => e.CategoryTriChid).HasColumnName("categoryTriCHId");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("categoryName");
            entity.Property(e => e.ParentId).HasColumnName("parentID");
            entity.Property(e => e.Slug)
                .HasMaxLength(100)
                .HasColumnName("slug");
            entity.Property(e => e.Status)
                .HasDefaultValue((byte)1)
                .HasColumnName("status");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Category_Parent");
        });

        modelBuilder.Entity<CustomerSupportQuiTh>(entity =>
        {
            entity.HasKey(e => e.SupportQuiThid).HasName("PK__Customer__6EAE6EED9C8AE241");

            entity.ToTable("CustomerSupportQuiTH");

            entity.Property(e => e.SupportQuiThid).HasColumnName("supportQuiTHId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.IssueType)
                .HasMaxLength(100)
                .HasColumnName("issueType");
            entity.Property(e => e.OrderQuiThid).HasColumnName("orderQuiTHId");
            entity.Property(e => e.Resolution).HasColumnName("resolution");
            entity.Property(e => e.ReviewQuiThid).HasColumnName("reviewQuiTHId");
            entity.Property(e => e.StaffId).HasColumnName("staffId");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("OPEN")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerSupportQuiThCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerSupport_Customer");

            entity.HasOne(d => d.OrderQuiTh).WithMany(p => p.CustomerSupportQuiThs)
                .HasForeignKey(d => d.OrderQuiThid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerSupport_Order");

            entity.HasOne(d => d.ReviewQuiTh).WithMany(p => p.CustomerSupportQuiThs)
                .HasForeignKey(d => d.ReviewQuiThid)
                .HasConstraintName("FK_CustomerSupport_OrderReview");

            entity.HasOne(d => d.Staff).WithMany(p => p.CustomerSupportQuiThStaffs)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerSupport_Staff");
        });

        modelBuilder.Entity<LensServicePhuHn>(entity =>
        {
            entity.HasKey(e => e.ServicePhuHnid).HasName("PK__LensServ__EA3A8410DDCB618C");

            entity.ToTable("LensServicePhuHN");

            entity.Property(e => e.ServicePhuHnid).HasColumnName("servicePhuHNId");
            entity.Property(e => e.CoatingType)
                .HasMaxLength(50)
                .HasColumnName("coatingType");
            entity.Property(e => e.LensTypeId).HasColumnName("lensTypeID");
            entity.Property(e => e.PrescriptionPhuHnid).HasColumnName("prescriptionPhuHNId");
            entity.Property(e => e.ServicePrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("servicePrice");

            entity.HasOne(d => d.PrescriptionPhuHn).WithMany(p => p.LensServicePhuHns)
                .HasForeignKey(d => d.PrescriptionPhuHnid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LensService_Prescription");
        });

        modelBuilder.Entity<OrderItemNamtmh>(entity =>
        {
            entity.HasKey(e => e.OrderItemNamtmhId).HasName("PK__OrderIte__ED596363E685CAB7");

            entity.ToTable("OrderItemNamtmh");

            entity.Property(e => e.OrderItemNamtmhId).HasColumnName("orderItemNamtmhID");
            entity.Property(e => e.OrderNamtmhId).HasColumnName("orderNamtmhID");
            entity.Property(e => e.PrescriptionId).HasColumnName("prescriptionID");
            entity.Property(e => e.ProductTriChid).HasColumnName("productTriCHID");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UnitPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("unitPrice");
            entity.Property(e => e.VariantId).HasColumnName("variantID");

            entity.HasOne(d => d.OrderNamtmh).WithMany(p => p.OrderItemNamtmhs)
                .HasForeignKey(d => d.OrderNamtmhId)
                .HasConstraintName("FK_OrderItemNamtmh_Order");

            entity.HasOne(d => d.ProductTriCh).WithMany(p => p.OrderItemNamtmhs)
                .HasForeignKey(d => d.ProductTriChid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemNamtmh_Product");
        });

        modelBuilder.Entity<OrderNamtmh>(entity =>
        {
            entity.HasKey(e => e.OrderNamtmhId).HasName("PK__OrderNam__CF25ED8212A63EE0");

            entity.ToTable("OrderNamtmh");

            entity.HasIndex(e => e.OrderNumber, "UQ__OrderNam__6296129F798261F5").IsUnique();

            entity.Property(e => e.OrderNamtmhId).HasColumnName("orderNamtmhID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerID");
            entity.Property(e => e.DiscountAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("discountAmount");
            entity.Property(e => e.FinalAmount)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("finalAmount");
            entity.Property(e => e.OrderNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("orderNumber");
            entity.Property(e => e.OrderStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("orderStatus");
            entity.Property(e => e.OrderType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("orderType");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("paymentMethod");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("paymentStatus");
            entity.Property(e => e.ShippingAddress).HasColumnName("shippingAddress");
            entity.Property(e => e.ShippingFee)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("shippingFee");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("totalAmount");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Customer).WithMany(p => p.OrderNamtmhs)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderNamtmh_User");
        });

        modelBuilder.Entity<OrderReviewQuiTh>(entity =>
        {
            entity.HasKey(e => e.ReviewQuiThid).HasName("PK__OrderRev__35676FF863E07BB2");

            entity.ToTable("OrderReviewQuiTH");

            entity.Property(e => e.ReviewQuiThid).HasColumnName("reviewQuiTHId");
            entity.Property(e => e.ContactMethod)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("contactMethod");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerContacted)
                .HasDefaultValue(false)
                .HasColumnName("customerContacted");
            entity.Property(e => e.IssueNote).HasColumnName("issueNote");
            entity.Property(e => e.OrderQuiThid).HasColumnName("orderQuiTHId");
            entity.Property(e => e.PrescriptionId).HasColumnName("prescriptionId");
            entity.Property(e => e.ReviewStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("reviewStatus");
            entity.Property(e => e.ReviewType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("reviewType");
            entity.Property(e => e.ReviewedAt)
                .HasColumnType("datetime")
                .HasColumnName("reviewedAt");
            entity.Property(e => e.StaffId).HasColumnName("staffId");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.OrderQuiTh).WithMany(p => p.OrderReviewQuiThs)
                .HasForeignKey(d => d.OrderQuiThid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderReview_Order");

            entity.HasOne(d => d.Prescription).WithMany(p => p.OrderReviewQuiThs)
                .HasForeignKey(d => d.PrescriptionId)
                .HasConstraintName("FK_OrderReview_Prescription");

            entity.HasOne(d => d.Staff).WithMany(p => p.OrderReviewQuiThs)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderReview_Staff");
        });

        modelBuilder.Entity<PrescriptionPhuHn>(entity =>
        {
            entity.HasKey(e => e.PrescriptionPhuHnid).HasName("PK__Prescrip__4B09949580507E65");

            entity.ToTable("PrescriptionPhuHN");

            entity.Property(e => e.PrescriptionPhuHnid).HasColumnName("prescriptionPhuHNId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerID");
            entity.Property(e => e.IsCustomLens)
                .HasDefaultValue(true)
                .HasColumnName("isCustomLens");
            entity.Property(e => e.LeftEyeAxis).HasColumnName("leftEyeAxis");
            entity.Property(e => e.LeftEyeCyl)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("leftEyeCyl");
            entity.Property(e => e.LeftEyeSph)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("leftEyeSph");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .HasColumnName("note");
            entity.Property(e => e.OrderItemNamtmhId).HasColumnName("orderItemNamtmhID");
            entity.Property(e => e.OrderNamtmhId).HasColumnName("orderNamtmhID");
            entity.Property(e => e.PupillaryDistance)
                .HasColumnType("decimal(4, 1)")
                .HasColumnName("pupillaryDistance");
            entity.Property(e => e.RightEyeAxis).HasColumnName("rightEyeAxis");
            entity.Property(e => e.RightEyeCyl)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("rightEyeCyl");
            entity.Property(e => e.RightEyeSph)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("rightEyeSph");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("totalPrice");

            entity.HasOne(d => d.OrderItemNamtmh).WithMany(p => p.PrescriptionPhuHns)
                .HasForeignKey(d => d.OrderItemNamtmhId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prescription_OrderItem");

            entity.HasOne(d => d.OrderNamtmh).WithMany(p => p.PrescriptionPhuHns)
                .HasForeignKey(d => d.OrderNamtmhId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prescription_Order");
        });

        modelBuilder.Entity<ProductReviewMiLtt>(entity =>
        {
            entity.HasKey(e => e.ReviewMiLttid).HasName("PK__ProductR__AF5DDFECA28A12D9");

            entity.ToTable("ProductReviewMiLTT");

            entity.Property(e => e.ReviewMiLttid).HasColumnName("reviewMiLTTId");
            entity.Property(e => e.Comment)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsVerified)
                .HasDefaultValue(false)
                .HasColumnName("isVerified");
            entity.Property(e => e.LikeCount)
                .HasDefaultValue(0)
                .HasColumnName("likeCount");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Order).WithMany(p => p.ProductReviewMiLtts)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Order");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductReviewMiLtts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Product");

            entity.HasOne(d => d.User).WithMany(p => p.ProductReviewMiLtts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_User");
        });

        modelBuilder.Entity<ProductTriCh>(entity =>
        {
            entity.HasKey(e => e.ProductTriChid).HasName("PK__ProductT__A722973C3B6BE871");

            entity.ToTable("ProductTriCH");

            entity.HasIndex(e => e.Sku, "UQ__ProductT__DDDF4BE732034D67").IsUnique();

            entity.Property(e => e.ProductTriChid).HasColumnName("productTriCHId");
            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("brand");
            entity.Property(e => e.CategoryTriChid).HasColumnName("categoryTriCHId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Dimensions)
                .HasMaxLength(30)
                .HasColumnName("dimensions");
            entity.Property(e => e.FrameType)
                .HasMaxLength(30)
                .HasColumnName("frameType");
            entity.Property(e => e.Material)
                .HasMaxLength(50)
                .HasColumnName("material");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("productName");
            entity.Property(e => e.Sku)
                .HasMaxLength(50)
                .HasColumnName("sku");
            entity.Property(e => e.Status)
                .HasDefaultValue((byte)1)
                .HasColumnName("status");
            entity.Property(e => e.StockQuantity)
                .HasDefaultValue(0)
                .HasColumnName("stockQuantity");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.CategoryTriCh).WithMany(p => p.ProductTriChes)
                .HasForeignKey(d => d.CategoryTriChid)
                .HasConstraintName("FK_ProductTriCH_CategoryTriCH");
        });

        modelBuilder.Entity<ProductionSonKn>(entity =>
        {
            entity.HasKey(e => e.ProductionSonKnid).HasName("PK__Producti__10BAB720E212B5A4");

            entity.ToTable("ProductionSonKN");

            entity.Property(e => e.ProductionSonKnid).HasColumnName("ProductionSonKNId");
            entity.Property(e => e.AssignedToSonKn).HasColumnName("AssignedToSonKN");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsUrgent).HasDefaultValue(false);
            entity.Property(e => e.OrderSonKnid).HasColumnName("OrderSonKNID");
            entity.Property(e => e.ProductionCode).HasMaxLength(50);
            entity.Property(e => e.ProductionNote).HasMaxLength(500);
            entity.Property(e => e.ProductionStatus).HasMaxLength(20);
            entity.Property(e => e.ShipmentSonKnid).HasColumnName("ShipmentSonKNId");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.AssignedToSonKnNavigation).WithMany(p => p.ProductionSonKns)
                .HasForeignKey(d => d.AssignedToSonKn)
                .HasConstraintName("FK_ProductionSonKN_Staff");

            entity.HasOne(d => d.OrderSonKn).WithMany(p => p.ProductionSonKns)
                .HasForeignKey(d => d.OrderSonKnid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionSonKN_Order");

            entity.HasOne(d => d.ShipmentSonKn).WithMany(p => p.ProductionSonKns)
                .HasForeignKey(d => d.ShipmentSonKnid)
                .HasConstraintName("FK_ProductionSonKN_Shipment");
        });

        modelBuilder.Entity<RefundTaiNd>(entity =>
        {
            entity.HasKey(e => e.RefundIdtaiNd).HasName("PK__RefundTa__47F6C65865BFB705");

            entity.ToTable("RefundTaiND");

            entity.Property(e => e.RefundIdtaiNd).HasColumnName("refundIDTaiND");
            entity.Property(e => e.RefundAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("refundAmount");
            entity.Property(e => e.RefundDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("refundDate");
            entity.Property(e => e.RefundMethod)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("refundMethod");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("transactionID");
        });

        modelBuilder.Entity<ReviewImageMiLtt>(entity =>
        {
            entity.HasKey(e => e.ImageMiLttid).HasName("PK__ReviewIm__DC229759ACAADC49");

            entity.ToTable("ReviewImageMiLTT");

            entity.Property(e => e.ImageMiLttid).HasColumnName("imageMiLTTId");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("imageURL");
            entity.Property(e => e.ReviewMiLttid).HasColumnName("reviewMiLTTId");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("uploadedAt");

            entity.HasOne(d => d.ReviewMiLtt).WithMany(p => p.ReviewImageMiLtts)
                .HasForeignKey(d => d.ReviewMiLttid)
                .HasConstraintName("FK_Image_Review");
        });

        modelBuilder.Entity<ShipmentSonKn>(entity =>
        {
            entity.HasKey(e => e.ShipmentSonKnid).HasName("PK__Shipment__83D5390FB7CB7EBA");

            entity.ToTable("ShipmentSonKN");

            entity.Property(e => e.ShipmentSonKnid).HasColumnName("ShipmentSonKNId");
            entity.Property(e => e.IsDelivered).HasDefaultValue(false);
            entity.Property(e => e.ShippingCompany).HasMaxLength(100);
            entity.Property(e => e.TrackingNumber)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId).HasName("PK__UserAcco__DA6C70BA6D086368");

            entity.ToTable("UserAccount");

            entity.HasIndex(e => e.UserName, "UQ__UserAcco__C9F284561C93948B").IsUnique();

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RequestCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}