// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class AfterSalesTaiNd
{
    public int RequestIdtaiNd { get; set; }

    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public string RequestType { get; set; }

    public string Reason { get; set; }

    public string RequestStatus { get; set; }

    public decimal? RefundAmount { get; set; }

    public int? ExchangeProductId { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public int? ProcessedBy { get; set; }

    public string ResolutionNotes { get; set; }

    public int? RefundIdtaiNd { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrderNamtmh Order { get; set; }

    public virtual UserAccount ProcessedByNavigation { get; set; }

    public virtual RefundTaiNd RefundIdtaiNdNavigation { get; set; }
}