// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class LensServicePhuHn
{
    public int ServicePhuHnid { get; set; }

    public int PrescriptionPhuHnid { get; set; }

    public int LensTypeId { get; set; }

    public string CoatingType { get; set; }

    public decimal ServicePrice { get; set; }

    public virtual PrescriptionPhuHn PrescriptionPhuHn { get; set; }
}