// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class PrescriptionPhuHn
{
    public int PrescriptionPhuHnid { get; set; }

    public int OrderNamtmhId { get; set; }

    public int OrderItemNamtmhId { get; set; }

    public int CustomerId { get; set; }

    public decimal? RightEyeSph { get; set; }

    public decimal? RightEyeCyl { get; set; }

    public int? RightEyeAxis { get; set; }

    public decimal? LeftEyeSph { get; set; }

    public decimal? LeftEyeCyl { get; set; }

    public int? LeftEyeAxis { get; set; }

    public decimal? PupillaryDistance { get; set; }

    public bool IsCustomLens { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<LensServicePhuHn> LensServicePhuHns { get; set; } = new List<LensServicePhuHn>();

    public virtual OrderItemNamtmh OrderItemNamtmh { get; set; }

    public virtual OrderNamtmh OrderNamtmh { get; set; }

    public virtual ICollection<OrderReviewQuiTh> OrderReviewQuiThs { get; set; } = new List<OrderReviewQuiTh>();
}