// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ProductColorTriCh
{
    public int ColorTriChid { get; set; }

    public int ProductTriChid { get; set; }

    public string ColorName { get; set; }

    public string ColorCode { get; set; }

    public int? StockQuantity { get; set; }

    public virtual ICollection<ProductImageTriCh> ProductImageTriChes { get; set; } = new List<ProductImageTriCh>();

    public virtual ProductTriCh ProductTriCh { get; set; }
}