// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class ProductionSonKn
{
    public int ProductionSonKnid { get; set; }

    public int OrderSonKnid { get; set; }

    public int? AssignedToSonKn { get; set; }

    public string ProductionCode { get; set; }

    public string ProductionNote { get; set; }

    public string ProductionStatus { get; set; }

    public bool? IsUrgent { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? ExpectedFinishDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? ShipmentSonKnid { get; set; }

    public virtual UserAccount AssignedToSonKnNavigation { get; set; }

    public virtual OrderNamtmh OrderSonKn { get; set; }

    public virtual ShipmentSonKn ShipmentSonKn { get; set; }
}