// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlassStore.Entities.TriCH.Models;

public partial class RefundTaiNd
{
    public int RefundIdtaiNd { get; set; }

    public string RefundMethod { get; set; }

    public decimal RefundAmount { get; set; }

    public DateTime? RefundDate { get; set; }

    public string TransactionId { get; set; }

    public virtual ICollection<AfterSalesTaiNd> AfterSalesTaiNds { get; set; } = new List<AfterSalesTaiNd>();
}